### ISSUE TITLE
Error thrown when trying to build project

### ISSUE THREAD

**Issue by kennyek** [elmonashodie/electronfrontend#2]
Scripts `electron-pack` and `electron-dist` in _package.json_ throws error.

## Expected Behavior

A build is created.

## Current Behavior

An error is thrown as follows:

```bash
Error: Application entry file "build/electron.js" in the "/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/out/asar/asarFileChecker.js:44:14)
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:30:4
    at Generator.next (<anonymous>)
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:160:5)
From previous event:
    at _checkFileInArchive (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:36:17)
    at checkFileInArchive (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/out/asar/asarFileChecker.js:40:30)
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/platformPackager.ts:409:13
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.checkFileInPackage (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/platformPackager.ts:406:110)
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/platformPackager.ts:460:16
    at Generator.next (<anonymous>)
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:160:5)
From previous event:
    at LinuxPackager.sanityCheckPackage (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/platformPackager.ts:446:92)
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/platformPackager.ts:249:16
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at LinuxPackager.doPack (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.pack (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:160:5)
From previous event:
    at Packager.doBuild (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:146:20)
From previous event:
    at Packager._build (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/home/kenny/Dev/open-source/elmonashodie/electronfrontend-fork/node_modules/electron-builder/src/cli/cli.ts:49:19)
```

## Possible Solution

The error message states "_Seems like a wrong configuration._", so perhaps revise how to build using `electron-builder`.

## Steps to Reproduce

1. Clone the repo and change into its directory.
2. Install dependencies with `npm install`.
3. Run either `electron-pack` or `electron-dist`.

**Comment by Elmona** [comment]
Great job!
